branch-defaults:
  default:
    environment: udagram-api-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-api
  branch: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
